export interface SocketQueueEvent {
	queueId?: string;
}

export interface ISocketEvent {
	event: ISocketEventType;
	data: any;
}

export type ISocketEventType =
	| "WORKER_JOINED_QUEUE"
	| "WORKER_NOT_OWNER"
	| "WORKER_IS_NOT_IN_QUEUE"
	| "USER_IS_NOT_WORKER"
	| "QUEUE_NOT_FOUND"
	| "QUEUE_CUSTOMER_NOT_FOUND"
	| "QUEUE_CUSTOMER_NOT_CREATED"
	| "QUEUE_CUSTOMER_IS_NOT_IN_QUEUE"
	| "QUEUE_FINISHED"
	| "QUEUE_PAUSED"
	| "QUEUE_RESUMED"
	| "QUEUE_OFF"
	| "QUEUE_CUSTOMER_SERVED"
	| "QUEUE_CUSTOMER_MISSED"
	| "QUEUE_CUSTOMER_REMOVED"
	| "QUEUE_CUSTOMER_DENIED"
	| "QUEUE_CUSTOMER_APPROVED"
	| "QUEUE_CUSTOMER_JOINED"
	;
